### ISSUE TITLE
Rim Weighting error: Variable "category" is unsuitable for Weighting. 

### ISSUE THREAD

**Issue by jtamerius** [Quantipy/quantipy3#11]
Hey All,

I am trying to do some rim weighting. Here is my code...

```
    ##create quantipy dataset from pandas dataframe
    dataset = qp.DataSet(name='example', dimensions_comp=False)
    dataset.from_components(df_srv)

    ##create rim scheme
    scheme = qp.Rim('my_first_scheme')

    #create targets for rim weighting from population dataset
    category_targets = {}
    temp = df_apps['category'].value_counts(normalize=True).reset_index(drop=True)
    temp.index += 1 # I thought the zero-index might be the issue so this starts index from 1
    category_targets['category'] = temp.to_dict()
    scheme.set_targets(targets=category_targets, group_name='basic weights')
    dataset.weight(scheme, weight_name='weights_new', unique_key='cvrp_id') ##cvrp_id is unique
```
Here are the contents of _category_targets_:
`{'category': {1: 0.619027907888717, 2: 0.34975999070463243, 3: 0.031212101406650546}}`

I am getting the following error message: 
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\james.tamerius\Desktop\qc_jt\quantipy3\quantipy\core\dataset.py", line 3025, in weight
    engine.add_scheme(weight_scheme, key=unique_key, verbose=verbose)
  File "C:\Users\james.tamerius\Desktop\qc_jt\quantipy3\quantipy\core\weights\weight_engine.py", line 202, in add_scheme
    scheme._minimize_columns(self._df, key, verbose)
  File "C:\Users\james.tamerius\Desktop\qc_jt\quantipy3\quantipy\core\weights\rim.py", line 311, in _minimize_columns
    self._check_targets(verbose)
  File "C:\Users\james.tamerius\Desktop\qc_jt\quantipy3\quantipy\core\weights\rim.py", line 433, in _check_targets
    raise ValueError(vartype_err.format(self.name, group, target_col))
ValueError: *** Stopping: Scheme "my_first_scheme", group "basic weights" ***
Variable "category" is unsuitable for Weighting.
Target variables must be of type integer (convertable) / single categorical.
```

Any help would be much appreciated!

**Comment by geirfreysson** [comment]
Hi James.

What is the output if you run

```dataset.meta('category')```

I'm curious because quantipy is complaining about the type of variable you are setting as the weight target. It needs to be a categorical (not a string, for example).

**Comment by jtamerius** [comment]
Here is the ouput:

```
dataset.meta('category')

           string
category:     N/A

```
I changed to categorical and it is working now...thanks!

**Comment by geirfreysson** [comment]
Great! Just make sure (by using `datasource.meta("category")` after conversion) that the codes that are created when you convert the variable to a single/categorical match the numbers you expect (it should, if memory serves).
