### ISSUE TITLE
dimensions file not loading properly

### ISSUE THREAD

**Issue by SauravK1996** [Quantipy/quantipy3#46]
Traceback (most recent call last):
  File "F:\Python\data.py", line 5, in <module>
    meta, data = qp.read_dimensions('KAP2.mdd','KAP2.ddf')
  File "C:\Program Files\Python37\lib\site-packages\quantipy\core\tools\dp\io.py", line 300, in read_dimensions
    meta, data = quantipy_from_dimensions(path_mdd, path_ddf)
  File "C:\Program Files\Python37\lib\site-packages\quantipy\core\tools\dp\dimensions\reader.py", line 976, in quantipy_from_dimensions
    ddf, levels = quantipy_clean(ddf_to_pandas(path_ddf))
  File "C:\Program Files\Python37\lib\site-packages\quantipy\core\tools\dp\dimensions\reader.py", line 147, in quantipy_clean
    if parent=='None':
  File "C:\Program Files\Python37\lib\site-packages\pandas\core\generic.py", line 1555, in __nonzero__
    self.__class__.__name__
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by SauravK1996** [comment]
import quantipy as qp

meta, data = qp.read_dimensions('KAP1.mdd','KAP1.ddf')
print(meta)

print(data)

**Comment by SauravK1996** [comment]
Above code is reading Museum.mdd and Museum.ddf files but not the one that I had given.
